#!/usr/bin/env bash

open_cmd=
repo=$(basename `pwd`)

if which xdg-open > /dev/null; then
  open_cmd=xdg-open
elif which gnome-open > /dev/null; then
  open_cmd=gnome-open
elif which open > /dev/null; then
  open_cmd=open
else:
  echo "No compatible 'open' commands found!"
  exit
fi

for row in `git-standup -m 2 -r origin|cut -d" " -f 1`; do
    if [[ ${row} == /* ]] ; then
        folder=${row##*/}
    elif [[ ${row} == "Seems" ]]
    then
        echo "Nothing to show!"
    else
        repo=$(git -C ${folder:-$(pwd)} config --get remote.origin.url)
        ${open_cmd} "${repo:0:-4}/commit/$row?diff=split"
        sleep 1
    fi
done
